name: API and App Deploy

on:
  push:
    branches:
      - main #Testing to trigger workflow

jobs:
  API:
    runs-on: ubuntu-latest #testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Test SSH connection to Hetzner VPS
      - name: Test SSH Connection to Hetzner VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@178.156.135.15 "echo 'SSH connection successful'"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
