name: API Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  API:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies in API
        run: |
          cd api
          npm install

      - name: Build API
        run: |
          cd api
          npm run build
          
      - name: Start API
        run: |
          cd api
          pm2 restart apiServer
      
  APP:
    needs: API
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies in App
        run: |
          cd app
          npm install

      - name: Build App
        run: |
          cd app
          CI=false npm run build
        env:
          REACT_APP_GOOGLE_CLIENT_KEY: ${{ secrets.REACT_APP_GOOGLE_CLIENT_KEY }}
          REACT_APP_GRAPHQL_URL: ${{ secrets.REACT_APP_GRAPHQL_URL }}

      - name: Start frontend Server
        run: |
          cd app
          pm2 restart frontendServer