name: API Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  API:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create dist directory
        run: |
          cd api
          mkdir -p dist

      - name: Install dependencies in API
        run: |
          cd api
          npm install

      - name: Build API
        run: |
          cd api
          npm run build

      - name: Start API
        run: |
          cd api
          pm2 restart apiServer || pm2 start apiServer --name apiServer

  APP:
    needs: API
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create dist directory for App
        run: |
          cd app
          mkdir -p dist

      - name: Install dependencies in App
        run: |
          cd app
          npm install

      - name: Build App
        run: |
          cd app
          CI=false npm run build

      - name: Start frontend Server
        run: |
          cd app
          pm2 restart frontendServer || pm2 start app --name frontendServer
