
name: API Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: Install dependencies in API
        run: |
          cd api
          npm install
      - name: Install dependencies in App
        run: |
          pwd
          cd ../app
          npm i
        
      
      
