
name: API Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  API:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Install dependencies in API
        run: |
          cd api
          npm install

  APP:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: Install dependencies in App
        run: |
          cd app
          npm i
      - name: Build App
        run: |
          cd app
          yarn build

      - name: Deploy to AWS S3
        run: |
          aws s3 sync app/build s3://accessability-artifacts --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'

      
      
