name: API and App Deploy

on:
  push:
    branches:
      - main #Testing to trigger workflow

jobs:
  API:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Test SSH connection to Hetzner VPS
      - name: Test SSH Connection to Hetzner VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@5.78.114.87 "echo 'SSH connection successful'"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
