
name: API Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  API:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Install dependencies in API
        run: |
          cd api
          npm install
          npm install ts-node
          pm2 stop all
          pm2 start server.ts --interpreter="./node_modules/.bin/ts-node"

  APP:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: Install dependencies in App
        run: |
          cd app
          npm i

          tsc
          pm2 restart server

      - name: Build App
        run: |
          cd app
          CI=false && npm run build

      - name: Install AWS CLI (Optional Step)
        run: |
          if ! command -v aws &> /dev/null
          then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
          fi
        shell: bash

      - name: Deploy to AWS S3
        run: |
          aws s3 sync app/build s3://accessability-artifacts --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CI: false
          AWS_REGION: 'us-east-2'

      
      
